# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

update_fastlane

default_platform(:ios)

platform :ios do

  desc "Run tests on all frameworks"
  lane :test_frameworks do
    scan(scheme: "FrameworksTests")
  end

  desc "Run unit tests on TimeTracker project"
  lane :test_unit do
    scan(scheme: "TimeTracker")
  end

  desc "Run UI tests on TimeTracker project"
  lane :test_ui do
    scan(scheme: "TimeTrackerUITests",
        devices: ["iPhone XS", "iPhone SE"])
  end

  desc "Run all tests"
  lane :test do 
    test_frameworks
    test_unit
    test_ui
  end

  desc "Create beta test version"
  lane :beta do
    test
    cert
    sigh(force: true)
    build_app(scheme: "TimeTracker",
              workspace: "TimeTracker.xcworkspace",
              clean: true,
              include_bitcode: true)
    upload_to_testflight
  end
end
